package:
  format-version: "1.0.0"
  name: "smartenergy_metrology_apps"
  version: "v1.0.0"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "smartenergy_metrology"
      type: "package"
      version: "v1.1.0"
    - name: "shd"
      type: "package"
      version: "v1.2.0"
    - name: "gfx"
      type: "package"
      version: "v3.16.1"
